const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  onWindowState: (cb) => ipcRenderer.on('window-state', (_, s) => cb(s)),
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  chooseFile: () => ipcRenderer.invoke('choose-file'),
  openFolder: (p) => ipcRenderer.send('open-folder', p),
  getDefaultDir: () => ipcRenderer.invoke('get-default-dir'),
  checkYtdlp: () => ipcRenderer.invoke('check-ytdlp'),
  checkFfmpeg: () => ipcRenderer.invoke('check-ffmpeg'),
  fetchInfo: (url) => ipcRenderer.invoke('fetch-info', url),
  startDownload: (job) => ipcRenderer.invoke('start-download', job),
  cancelDownload: (id) => ipcRenderer.send('cancel-download', id),
  onProgress: (cb) => ipcRenderer.on('download-progress', (_, d) => cb(d)),
  onLog: (cb) => ipcRenderer.on('download-log', (_, d) => cb(d)),
  convertFile: (job) => ipcRenderer.invoke('convert-file', job),
  onConvertProgress: (cb) => ipcRenderer.on('convert-progress', (_, d) => cb(d)),
  getVersion: () => ipcRenderer.invoke('get-version'),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  installUpdate: () => ipcRenderer.send('install-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, d) => cb(d)),
});
